### ISSUE TITLE
QA_Diagnostic Codes_Dev

### ISSUE THREAD

**Issue by tvinodreddy** [Ali-aqrabawi/ezclinic#101]
Previously selected Diagnostic Codes not showing while Editing Medical Details
![screenshot 2017-05-22 12 58 38](https://cloud.githubusercontent.com/assets/28854494/26297094/1db349d8-3eef-11e7-8a14-c8b2cb24b6a1.png)

**Comment by Ali-aqrabawi** [comment]
still don't see previously selected codes while editing 
![image](https://user-images.githubusercontent.com/17279421/28278881-4cd91756-6b27-11e7-9dcf-514c221388b1.png)


![image](https://user-images.githubusercontent.com/17279421/28278868-42e69e76-6b27-11e7-9a93-1efef732fe33.png)
